languaje: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - roddxns@gmail.com
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  #SONARCLOUD
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=roddxns-github


